baseURL = "https://clslaid.icu"
title = "ClSlaid"
theme = "hugo-notepadium"
copyright = "©2020 Notepadium."

languageCode = "en"  # for the RSS generation
defaultContentLanguage = "en"

hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
disqusShortname = "ClSlaid"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "2006-01-02"  # if unset, default is "2006-01-02"
readingTime = true  # show reading time after article date
logo = "asuka.jpg"
slogan = "老废物呜呜呜"
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."

[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.share]
enable = false  # En/Disable share globally, default: false. You can always enable share on per page.
addThisId = ""
inlineToolId = ""

[params.math]
enable = true # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.syntax]
use = "hljs"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "stackoverflow-light-adjust"
darkTheme = "atom-one-dark-reasonable"

[params.profile]
  enable = true
  avatar = "asuka.jpg"
  name = "ClSlaid"
  bio = "老废物呜呜呜"
  # support markdown syntax
  twitter = "ClSlaid"  # https://twitter.com/XXX
  github = "ClSlaid"  # https://github.com/XXX

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

[params.assets]
css = ["css/fonts.css", "css/iconfont.css"]

[[params.nav.custom]]
title = "About"
url = "/about/"

[[params.nav.custom]]
title = "Hugo"
url = "https://gohugo.io/"